version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: obagateam-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=obagateam
    volumes:
      - mongodb_data:/data/db
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB GUI - Mongo Express
  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: obagateam-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_SITE_BASEURL=/
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obagateam-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/obagateam
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obagateam-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  obagateam-network:
    driver: bridge