version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: obagateam-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=obagateam
    volumes:
      - mongodb_data:/data/db
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    image: ogegak2003/obagateam-backend:latest
    container_name: obagateam-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/obagateam
      - JWT_SECRET=${JWT_SECRET:-default-production-secret-change-me}
      - FRONTEND_URL=http://localhost
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    image: ogegak2003/obagateam-frontend:latest
    container_name: obagateam-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
      - VITE_APP_NAME=obagaTeam
      - VITE_APP_URL=http://localhost
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - obagateam-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  obagateam-network:
    driver: bridge