name: Deploy to Staging

on:
  push:
    branches: [ develop ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  BACKEND_IMAGE: obagateam-backend
  FRONTEND_IMAGE: obagateam-frontend

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push staging images
      run: |
        docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:staging -f backend/Dockerfile.prod backend/
        docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:staging
        
        docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:staging -f frontend/Dockerfile.prod frontend/
        docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:staging
    
    - name: Deploy to staging environment
      run: |
        echo "🚀 Deploying to staging environment..."
        # Add your staging deployment commands here
        # docker-compose -f docker-compose.staging.yml up -d